### ISSUE TITLE
How do you verify the data that is entered?

### ISSUE THREAD

**Issue by E3V3A** [mundanelunacy/covidmaps#18]
yep

**Comment by mundanelunacy** [comment]
yeah..... there probably should be a confirmation page

**Comment by mundanelunacy** [comment]
resolved on dev branch

**Comment by E3V3A** [comment]
Yes, but *HOW* is it "verified"? What do you mean  with verify?

**Comment by E3V3A** [comment]
@mundanelunacy ??
